[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [
    { access = "read", path = "./out" },
    { access = "read", path = "./scripts/vanityaddr/contracts" }
]

[fmt]
line_length = 120
multiline_func_header = 'all'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
